### ISSUE TITLE
Is it possible to return at most N nearest neighbors?

### ISSUE THREAD

**Issue by astrojhgu** [kornelski/vpsearch#1]
According to the API doc, there is a find_nearest function. However, by default, it can only return the nearest neighbor node. How can I find out at most N nearest neighbors? This is import for interpolation.

**Comment by kornelski** [comment]
There's no built-in function for this, but it is possible by customizing matching done in the library.

There's [`find_nearest_custom`](https://docs.rs/vpsearch/1.3.4/vpsearch/struct.Tree.html#method.find_nearest_custom) that takes a visitor:

https://github.com/kornelski/vpsearch/blob/c2730388437019b9a54d00667a66ac0a4b9afa03/src/lib.rs#L96-L102

and if you create your own implementation of that visitor:

https://github.com/kornelski/vpsearch/blob/c2730388437019b9a54d00667a66ac0a4b9afa03/src/lib.rs#L111-L130

you can collect _N_ elements instead of picking [one](https://github.com/kornelski/vpsearch/blob/c2730388437019b9a54d00667a66ac0a4b9afa03/src/lib.rs#L116).

**Comment by astrojhgu** [comment]
If I always keep N nearest visited nodes in my implementation of the BestCandidate trait, would it be guaranteed that after the find_nearest_custom function return, the N remaining nodes are the the nearest N's among all the nodes?

The reason why I'm curious about this question is that tree-like structure can trim unnecessary searching branches to speedup the search. What if the trimmed branches contain nodes that is among the N nearest ones?

**Comment by kornelski** [comment]
You're right! There's one more trick you have to do:

```rust
best_candidate.distance()
```

has to return distance of the Nth farthest node, which will force it to search everything in that radius.

**Comment by astrojhgu** [comment]
Hi, I tried to use vpsearch to do an N-Nearest Neighbor search on a sphere. The point is described in spherical coordinates (polarization angle, azimuth angle). I implemented the BestCandidate trait, and always keep N best candidates. The distance will return the Nth farthest node's distance. But I found that sometimes, less than N points will be returned.

More interesting thing is that if I change the coordinate from (90deg, -90deg) to (90deg, 270deg), which mathematically are identical, the result will be different. (90deg, -90deg) will not return enough points and (90deg, 270deg) is OK.

If you are convenient, you can checkout my minimum test codes at:
[a test case for vpsearch](https://github.com/astrojhgu/test_vp)

It is not so ``min'' (231 lines), but it has been the least code I can write to reproduce my problem.

Many thanks.

**Comment by gijs-s** [comment]
I found myself needing the same thing as described in this issue, I made a pull request adding examples on how to achieve this! See https://github.com/kornelski/vpsearch/pull/3.
